name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip test suite (emergency deploy only)'
        required: false
        default: 'false'
        type: boolean

concurrency:
  group: deploy-production
  cancel-in-progress: false

env:
  VM_ZONE: northamerica-northeast2-a
  VM_NAME: ${{ vars.VM_NAME }}
  GCP_PROJECT: ${{ vars.GCP_PROJECT }}
  DEPLOY_DIR: /opt/app

jobs:
  test:
    name: Run Tests
    if: ${{ github.event.inputs.skip_tests != 'true' }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: analytics_platform
          POSTGRES_USER: app_user
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt 2>/dev/null || true

      - name: Run test suite
        env:
          DATABASE_URL: postgresql://app_user:${{ secrets.DB_PASSWORD }}@localhost:5432/analytics_platform
          FLASK_DEBUG: '0'
          TESTING: 'true'
        run: pytest tests/ -v --tb=short

  deploy:
    name: Deploy to Production VM
    needs: [test]
    if: always() && (needs.test.result == 'success' || github.event.inputs.skip_tests == 'true')
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to VM
        run: |
          gcloud compute ssh ${{ env.VM_NAME }} \
            --zone=${{ env.VM_ZONE }} \
            --project=${{ env.GCP_PROJECT }} \
            --command="cd ${{ env.DEPLOY_DIR }} && bash scripts/deploy.sh" \
            --ssh-flag="-o StrictHostKeyChecking=no"

      - name: Smoke test
        run: |
          sleep 10
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" ${{ vars.APP_URL }}/api/engines)
          if [ "$HTTP_CODE" != "200" ]; then
            echo "Smoke test FAILED: returned $HTTP_CODE"
            exit 1
          fi
          echo "Smoke tests PASSED"

      - name: Post-deploy notification
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "::notice::Deployment to production SUCCEEDED"
          else
            echo "::error::Deployment to production FAILED"
          fi
